version: '3.3'

networks:
    portfolio:
        external:
          name: socialite

services:

  

  db:

    image: postgres:14.7
    container_name: socialite_postgres_database
    volumes: 
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks: 
      - portfolio
    ports:
       - "5432:5432"
  adminer:
    image: adminer
    container_name: socialite_adminer
    restart: always
    ports:
     - 8080:8080
    networks: 
     - portfolio
  django:
    image: django_docker:0.01
    container_name: socialite_django
    build: .
    ports:
     - "8000:8000"
    volumes:
      - .:/CODE
    command: >
       python3 manage.py runserver 0.0.0.0:8000 
    networks: 
    - portfolio
    depends_on:
    - db

volumes:
  db-data:



