# Generated by Django 4.2 on 2023-10-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('isbn', models.CharField(max_length=255)),
                ('isbn13', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=10)),
                ('num_pages', models.SmallIntegerField(default=0)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=255)),
                ('author', models.ManyToManyField(related_name='author', to='books.author')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
