# Use an official Node.js image as the base image
FROM node:18.16.0 AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire app directory to the container
COPY . .

# Build the Vite app for production
RUN npm run build

# Use a lightweight image for serving the app
FROM nginx:alpine

COPY my-nginx-config.conf /etc/nginx/conf.d/default.conf

# Copy the built app from the build container to the serving container
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Start the nginx server
CMD ["nginx", "-g", "daemon off;"]
